---
- name: Configure K8S Master
  hosts: all
  become: true

  tasks:
    - name: Pulling images required for setting up a Kubernetes cluster
      shell: kubeadm config images pull
    
    - name: Resetting kubeadm
      shell: kubeadm reset -f
      register: output

    - name: Storing Logs and Generated token for future purpose.
      copy: 
        content: "{{ output.stdout }}"
        dest: kubeadm_reset_file

    - name: Initializing Kubernetes cluster
      shell: kubeadm init --pod-network-cidr=192.168.0.0/16 --ignore-preflight-errors=NumCPU
      register: output

    - name: Storing Logs and Generated token for future purpose.
      copy: 
        content: "{{ output.stdout }}"
        dest: token_file
    
    - name: Copying required files
      shell: |
       mkdir -p $HOME/.kube
       cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
       chown $(id -u):$(id -g) $HOME/.kube/config
    
    - name: Install Network Add-on
      command: kubectl apply -f https://docs.projectcalico.org/v3.11/manifests/calico.yaml

    - name: Copy kube config from master to local jenkins
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: /var/lib/jenkins/ansible/k8s-setup/kube_config
        flat: yes

