---
- name: Playbook to install docker
  hosts: all
  become: true

  tasks:
    - name: apt update
      apt:
        update_cache: yes
    - name: Install a list of packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg2
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: apt update for docker
      apt:
        update_cache: yes
    - name: Install docker-ce
      apt:
        pkg:
          - containerd.io=1.2.13-1
          - docker-ce=5:19.03.8~3-0~ubuntu-bionic
          - docker-ce-cli=5:19.03.8~3-0~ubuntu-bionic
    - name: load daemon.json from file
      include_vars:
        file: daemon.json
        name: daemon_var
    - debug:
        var: daemon_var
    - name: write daemon.json to file
      copy: 
        content: "{{ daemon_var | to_nice_json }}" 
        dest: /etc/docker/daemon.json
    - name: create directory docker.service.d if it doesn't exist
      file:
        path: docker.service.d
        state: directory
    - name: restart service docker, in all cases, also issue daemon-reload to pick up config changes
      systemd:
        state: restarted
        daemon_reload: yes
        name: docker
