---
- name: Creation of ec2 instance
  hosts: localhost

  tasks:
    - name: Create a local kube config directory
      shell: |
       mkdir -p $HOME/.kube
       cp -f /var/lib/jenkins/ansible/k8s-setup/kube_config $HOME/.kube/config
       chown $(id -u):$(id -g) $HOME/.kube/config
    
    - pause:
        minutes: 1

    - name: Kubectl get nodes
      shell: kubectl get nodes
    
    - pause:
        minutes: 1
    
    - name: kubectl taint nodes --all node-role.kubernetes.io/master-
      shell: kubectl taint nodes --all node-role.kubernetes.io/master-
